### ISSUE TITLE
Get the previous results with a checkout

### ISSUE THREAD

**Issue by BlueCutOfficial** [mansona/lint-to-the-future-dashboard-action#10]
Currently, the lttf-dashboard action runs `lint-to-the-future` with the following option for previous results:

```
--previous-results https://${{ github.repository_owner }}.github.io/`cut -d'/' -f2 <<< ${{ github.repository }}`${{inputs.folder}}/data.json
```

This can be a problem for private Github pages, because as explained [in this documentation](https://docs.github.com/en/enterprise-cloud@latest/pages/getting-started-with-github-pages/changing-the-visibility-of-your-github-pages-site#about-subdomains-for-privately-published-sites), private GitHub pages are deployed to a unique subdomain generated by GitHub for security reasons. Therefore, the pages are not deployed to `${{ github.repository_owner }}.github.io/` and the previous data cannot be found there.

Since lttf-dashboard relies on [actions-gh-pages](https://github.com/peaceiris/actions-gh-pages), and actions-gh-pages supposes the existence of a deployment branch, it may be more generic to use this kind of checkout rather than pointing directly to an URL:
```
- name: Read previous Lttf data from the gh-pages branch
  uses: actions/checkout@v4
  with:
    ref: gh-pages
    sparse-checkout: lint-to-the-future/data.json
    path: pages
- run: npx lint-to-the-future output -o ./lttfOutput --rootUrl lint-to-the-future --previous-results pages/lint-to-the-future/data.json
```

What do you think?
